---
title: "Anime OC Plot"
author: "Kyle MacDonald"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)
```

```{r libraries, include=FALSE}
library(magrittr); library(stringr); library(cowplot); library(here); 
library(forcats)
library(tidyverse)
theme_set(ggthemes::theme_few())
```

### Read data

```{r}
d <- read_csv(here("data/03_summary_tables", "anime_gvals_oc_plot.csv"))
d_trial_level <- read_csv(here("data/03_summary_tables", "anime_trial_level.csv"))
d_model <- read_rds(here("data/03_summary_tables", "anime-posterior-samples.rds"))
```

```{r}
analysis.window.lower <- 0
analysis.window.upper <- 1100

d %<>% filter(Time.ms >= analysis.window.lower, Time.ms <= analysis.window.upper)
```

## Experiment 1

```{r}
breaks <- unique(d$Time.ms) %>% .[seq(1, length(.), 6)]

d_plot <-  d %>% 
  filter(experiment == "e1", trial_type == "familiar") %>% 
  mutate(cue_type = recode(cue_type, onomatopoeic = "onomatopoeic word",
                           vocalization = "animal vocalization",
                           name = "animal name"))
```


```{r}
e1_oc_plot <- d_plot %>% 
  ggplot(aes(x = Time.ms, y = mean, color = cue_type)) +
  geom_linerange(data = filter(d_plot, Time.ms %in% breaks), 
                  aes(ymin = summary_ci_lower, ymax = summary_ci_upper),
                 position = position_jitter(height = 0, width = 20),
                 size = 0.8, alpha = 0.8) +
  geom_line(size = 1.5) +
  ylim(0, 0.9) +
  xlim(analysis.window.lower, analysis.window.upper + 300) +
  annotate("text", x = 150, y = 0.75, label = "DOG") +
  annotate("text", x = 150, y = 0.65, label = "WOOF", color = "grey") +
  annotate("text", x = 150, y = 0.55, label = "[barking]", color = "darkgrey") +
  scale_color_grey() +
  directlabels::geom_dl(aes(label = cue_type), method=list("last.points")) +
  labs(y = "Prop. shifting to target", x = "Time (ms)") +
  guides(color = F) 

e1_oc_plot
```

### Modeling results

```{r}
e1_model_summary <- d_model$rt_e1 %>% 
  group_by(cue_type) %>% 
  summarise(m = mean(rt_scale_param),
            hdi_lower = quantile(rt_scale_param, probs = 0.05),
            hdi_upper = quantile(rt_scale_param, probs = 0.95)) %>% 
  mutate_if(.predicate = is.numeric, .funs = round, digits = 2)
```

```{r}
e1_rt_hyp_d <- d_model$rt_e1 %>% 
  select(-param_est) %>% 
  spread(key = cue_type, value = rt_scale_param) %>% 
  mutate(name_onomatopoeic_diff = name - onomatopoeia,
         name_vocalization_diff = name - vocalization,
         onomatopeic_vocalization_diff = onomatopoeia - vocalization) %>% 
  select(-name, - onomatopoeia, -vocalization) %>% 
  gather(key = ind_contrast, value = param_est, -sample_id) 

e1_rt_hyp_table <- e1_rt_hyp_d %>% 
  group_by(ind_contrast) %>% 
  summarise(m = mean(param_est),
            hdi_lower = quantile(param_est, probs = 0.025),
            hdi_upper = quantile(param_est, probs = 0.975)) %>% 
  mutate_if(.predicate = is.numeric, .funs = round, digits = 2)

prob_diff0 <- e1_rt_hyp_d %>% 
  group_by(ind_contrast) %>% 
  summarise(prob = mean(param_est < 0)) %>% 
  mutate_if(.predicate = is.numeric, .funs = round, digits = 4)
```

### Data and Model plot

```{r}
d_ss <- d_trial_level %>% 
  filter(experiment == "e1",
         Response == "D", 
         trial_type == "familiar",
         RT >= 300, RT <= 1800,
         GoodRT == T,
         GoodFirstGap == T,
         GoodLongestGap == T) %>% 
  group_by(Sub.Num, cue_type) %>% 
  summarise(m = mean(RT, na.rm = T))


d_trials <- d_trial_level %>% 
  filter(experiment == "e1",
         Response == "D", 
         trial_type == "familiar",
         RT >= 300, RT <= 1800,
         GoodRT == T,
         GoodFirstGap == T,
         GoodLongestGap == T)
```

Robust plots for group differences.

```{r}
## global plot variables
dec_width = 0.5
dec_size = 1.5
connector_size = dec_size - 0.9
connector_length <- 2.1
q_seq <- c(0.5)

p <- d_trial_level %>% 
  filter(experiment == "e1",
         Response == "D", 
         trial_type == "familiar",
         RT >= 200, RT <= 1800,
         GoodRT == T,
         GoodFirstGap == T,
         GoodLongestGap == T) %>% 
  ggplot(aes(x = cue_type, y = RT)) +
  ggbeeswarm::geom_quasirandom(shape = 21, width = 0.15, color = "black", 
                               fill = "darkgrey",
                               alpha = 0.5) + 
  labs(y = "RT (sec)", x = NULL) +
  lims(y = c(0, 2000)) 

# get model values
d_model_vals <- d_models$rt_e1 %>% 
  dplyr::rename(RT = rt_scale_param) %>% 
  mutate(cue_type = ifelse(cue_type == "onomatopoeia", "onomatopoeic", cue_type))

# get quantile vals
d_quantiles <- d_model_vals %>% 
  group_by(cue_type) %>% 
  summarise(val = hd(RT))

for (qi in 1:length(q_seq)) {
  p <- p + stat_summary(data = d_model_vals,
                        geom = "errorbar", 
                        fun.y = hd, fun.ymin = hd, fun.ymax = hd,
                        width = dec_width,
                        size = dec_size,
                        color = "black",
                        fun.args = list(q = q_seq[[qi]]))
}

p <- p + annotate("segment", 
             x = 1 + dec_width/2, xend = 2 - dec_width/2, 
             y = d_quantiles$val[1], yend = d_quantiles$val[2], 
             color = "red", 
             size = connector_size,
             alpha = 1) +
   annotate("segment", 
             x = 2 + dec_width/2, xend = 3 - dec_width/2, 
             y = d_quantiles$val[2], yend = d_quantiles$val[3], 
             color = "red", 
             size = connector_size,
             alpha = 1)
```

This is the old violin plot in case we want to go back to it. 

```{r, eval = F, include = F}
group_means_plot <- d_ss %>% 
  mutate(cue_type = recode(cue_type, onomatopoeic = "onomatopoeia")) %>% 
  ggplot(aes(x = cue_type, y = m)) +
  geom_violin(trim = F, width = 0.8, size = 1, draw_quantiles = c(0.5),
              color = "grey50", fill = "grey90") + 
  geom_jitter(color = "black", fill = "darkgrey", shape = 21, width = .03, size = 1.5,
              alpha = 0.5) +
  #geom_linerange(data = e1_model_summary, aes(ymin = hdi_lower, ymax = hdi_upper), 
   #               color = "darkred", fill = "red", size = 1) +  
  labs(x = "Cue Type", y = "RT (msec)") +
  scale_x_discrete(expand = c(0,0.8)) +
  lims(y = c(0, 2200)) 
```

```{r}
group_diff_plot <- e1_rt_hyp_d %>% 
  mutate(param_est = param_est * -1, 
         ind_contrast = recode(ind_contrast, 
                               name_onomatopoeic_diff = "name_onomatopeia",
                               name_vocalization_diff = "name_vocalization",
                               onomatopeic_vocalization_diff = "onomatopeia_vocalization"),
         ind_contrast_fact = factor(ind_contrast)) %>% 
  ggplot(aes(x = param_est, color = ind_contrast_fact, linetype = ind_contrast_fact)) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red", size = 1) +
  geom_line(stat = "density", size = 1) +
  scale_color_grey() +
  labs(x = "Difference in RT (msec)", y = "Density",
       color = "Contrast:",
       linetype = "Contrast:") +
  lims(x = c(-200,900)) + 
  theme(legend.position=c(.75, .7),
        legend.background = element_rect(fill = "transparent", colour = "transparent"),
        legend.key = element_rect(fill = "transparent", colour = "transparent"),
        legend.title = element_text(size=10),
        legend.text = element_text(size=8))
```

## Construct the final plot

```{r}
model_plots <- plot_grid(p, group_diff_plot, labels = c("b", "c"),
                         rel_widths = c(1.1, 1))

oc_plot <- plot_grid(e1_oc_plot, labels = "a")

final_plot <- plot_grid(oc_plot, model_plots, nrow = 2, 
                        rel_heights = c(1.2,1))
# print the plot
final_plot
```

```{r}
ggsave(final_plot, filename = here("paper/figs", "oc_e1_new.png"), 
       width = 8.3, height = 5)
```
