---
title: "Anime Profile Plots"
author: "Kyle MacDonald"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = T, message = F, warning = F)
theme_set(ggthemes::theme_few())
```

```{r libraries, include=FALSE}
library(lme4); library(langcog); library(magrittr)
library(kmr); library(stringr); library(gridExtra); 
library(tidyverse)
```

### Read data

```{r}
df <- read_csv("../../data/summary_tables/anime_gvals.csv")
```

```{r}
analysis.window.lower <- 0
analysis.window.upper <- 2500
```

```{r}
df %<>% filter(Time.ms >= analysis.window.lower, Time.ms <= analysis.window.upper)
```

## Experiment 1

```{r filter e1}
e1_df <- filter(df, experiment == "experiment_1")
```

### Target looking over time

```{r}
e1_df %>% 
  filter(value_cat == "Target") %>% 
  ggplot(aes(x = Time.ms, y = m_prop_looking, color = cue_type)) +
  geom_line(size = 1) +
  scale_color_grey() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  directlabels::geom_dl(aes(label = cue_type), method=list("last.qp")) +
  labs(y = "Prop. Target Looking", x = "Time (ms)") +
  guides(color = F) + 
  ylim(0.4, 0.8) +
  xlim(0, 3000) +
  facet_wrap(~trial_type)
```

## Experiment 2

```{r filter e2}
e2_df <- filter(df, experiment == "experiment_2_retention")
```

### Target looking over time

```{r target looking e2}
df_e2_filt <- filter(e2_df, Time.ms >= analysis.window.lower, 
                     Time.ms <= analysis.window.upper, value_cat == "Target")

df_e2_filt %>% 
  filter(value_cat == "Target") %>% 
  ggplot(aes(x = Time.ms, y = m_prop_looking, color = trial_type)) +
  geom_line(size = 1) +
  scale_color_grey() +
  geom_hline(yintercept = 0.5, linetype = "dashed") +
  directlabels::geom_dl(aes(label = trial_type), method=list("last.qp")) +
  labs(y = "Prop. Target Looking", x = "Time (ms)") +
  guides(color = F) + 
  ylim(0.4, 0.8) +
  xlim(0, 3000) 
```
